# Age Group VS Sentence

In [1]:
import os
import sys
import pandas as pd

sys.path.append("..")
from src.create_agegroup_minimal_pair import create_age_minimal_pairs_age
from src.create_agegroup_minimal_pair import create_age_minimal_pairs_year

create_age_minimal_pairs_age("../data/offense.csv")
create_age_minimal_pairs_year("../data/offense.csv")

# 2 pairs of sentences, 5 templates,
# 8 age groups
# 4 years

Saved age-group minimal pairs (AGE ROI) to ../data/age_minimal_pairs_age.tsv
Total sentences generated: 237440
Saved age-group minimal pairs (YEAR ROI) to ../data/age_minimal_pairs_year.tsv
Total sentences generated: 237440

In [2]:
age = pd.read_csv("../data/age_minimal_pairs_age.tsv", sep="\t")
year = pd.read_csv("../data/age_minimal_pairs_year.tsv", sep="\t")

In [3]:
display(age.head())
display(year.head())

,sentid,pairid,comparison,sentence,age_pair,age_group,years,ROI,template_id
0,0,0,expected,The person who committed Aggravated Assault Kn...,22-30 vs 61-70,22-30,0,12,1
1,1,0,unexpected,The person who committed Aggravated Assault Kn...,22-30 vs 61-70,61-70,0,12,1
2,2,1,expected,The defendant was found guilty of Aggravated A...,22-30 vs 61-70,22-30,0,15,2
3,3,1,unexpected,The defendant was found guilty of Aggravated A...,22-30 vs 61-70,61-70,0,15,2
4,4,2,expected,The individual sentenced to 0 years for Aggrav...,22-30 vs 61-70,22-30,0,11,3

,sentid,pairid,comparison,sentence,age_pair,age_group,years,ROI,template_id
0,0,0,expected,A person aged 22-30 committed Aggravated Assau...,22-30 vs 61-70,22-30,0,12,1
1,1,0,unexpected,A person aged 61-70 committed Aggravated Assau...,22-30 vs 61-70,61-70,0,12,1
2,2,1,expected,The defendant aged 22-30 was found guilty of A...,22-30 vs 61-70,22-30,0,15,2
3,3,1,unexpected,The defendant aged 61-70 was found guilty of A...,22-30 vs 61-70,61-70,0,15,2
4,4,2,expected,"For the crime of Aggravated Assault Knowingly,...",22-30 vs 61-70,22-30,0,16,3